services:
  tileserver-gl:
    container_name: tileserver-gl
    image: stsdockerhub/tileserver-gl-light:5.7.0-pre.0
    volumes:
      - "./data:/data"
    command: [ "--verbose", "--config", "/data/config.json" ]
    ports:
      - "8081:8080"