version: '3.7'

services:
  tileserver-gl:
    container_name: tileserver-gl
    image: maptiler/tileserver-gl:v4.10.3
    volumes:
      - "./data:/data"
    command: [ "--verbose", "--config", "/data/config.json" ]
    ports:
      - "8080:8080"